# backend:
#   name: github
#   repo: zafarhusanov/astro
#   branch: main

backend:
  name: github
  repo: zafarhusanov/astro
  branch: main
  auth_type: implicit
  app_id: Ov23liDJrEd5YmFeBag5

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # English Pages
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "src/content/en"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Uzbek Pages
  - name: "pages_uz"
    label: "Pages (UZ)"
    folder: "src/content/uz"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
