backend:
  name: github       # Netlify Identity + Git Gateway
  repo: ZafarHusanov/astro
  branch: main            # asosiy branch
  commit_messages:        # commit xabarlari
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  # English Pages
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "src/content/en"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Uzbek Pages
  - name: "pages_uz"
    label: "Pages (UZ)"
    folder: "src/content/uz"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
