backend:
  name: github
  repo: ZafarHusanov/astro
  branch: main
  auth_scope: repo
  base_url: https://astro-mauve-six.vercel.app
  auth_endpoint: /api/auth
  cms_label_prefix: cms

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # English Pages
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "src/content/en"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Uzbek Pages
  - name: "pages_uz"
    label: "Pages (UZ)"
    folder: "src/content/uz"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
